mdapipkg/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Booth__c</fullName>
        <label>Booth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/App_Interest__c.object
<CustomObject>
    <fields>
        <fullName>App_Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>App Listing</label>
        <referenceTo>App_Listing__c</referenceTo>
        <relationshipLabel>App Interests</relationshipLabel>
        <relationshipName>App_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>App Interests</relationshipLabel>
        <relationshipName>App_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>App Interest</label>
    <nameField>
        <displayFormat>AI-{000000}</displayFormat>
        <label>App Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/App_Listing__c.object
<CustomObject>
    <fields>
        <fullName>App_by_Partner__c</fullName>
        <formula>LEFT(Short_Name__c&amp; &quot; by &quot; &amp; Partner__r.Name, 80)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>App by Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Description__c</fullName>
        <label>Full Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Listing_Id__c</fullName>
        <label>Listing Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>App Listings</relationshipLabel>
        <relationshipName>App_Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pricing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <formula>LEFT( Brief_Desription__c , 100)</formula>
        <label>Short Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <formula>if(Len(Name)&lt;50, Name,

LEFT( Name , find(&quot; &quot;,left(Name,50),40))&amp;&quot;...&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Short Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tagline__c</fullName>
        <label>Tagline</label>
        <type>TextArea</type>
    </fields>
    <label>App Listing</label>
    <nameField>
        <label>App LIsting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppListingController.cls
global class AppListingController {
    	
  	@AuraEnabled
	public static List<App_Listing__c> getAppListing() {
		return [SELECT id, Short_Name__c , Name, App_by_Partner__c, Tagline__c, Full_Description__c, Short_Description__c, Listing_Id__c, Pricing__c, Rating__c, Partner__r.Booth__c, Partner__r.Name
			FROM App_Listing__c 
			ORDER BY Name];
	  }

    //this is incomplete and need to be updated to work with the EmailLead Lightning Component
    //Should Create a Lead, and Associated App Interest Objects.
    @AuraEnabled
    public static Lead saveLead(String firstName, String emailId, String country, List<Id> appIds) {
        system.debug('Enter SaveLead');
        List<Lead> li = new list <Lead>();
        Lead l = new Lead();
        l.FirstName = firstName;
        l.LastName = 'a';
        l.Company = 'NA';
        l.Email = emailId; 
        l.Country = country;
        li.add(l);
        system.debug(li);
   		upsert li;

        ID leadId = li[0].ID;
		system.debug(leadId);
        
       //Inserting App interests with the Lead id 
        List<App_Interest__c > appIntList = new list <App_Interest__c >();
        Integer idList = appIds.size();
        system.debug('appIds>>>'+ appIds);
        system.debug('number of apps>>>'+ idList);
        
        for(Integer i=0;i<idList;i++) {
    		App_Interest__c  ai = new App_Interest__c();
        	ai.Lead__c =leadId ;
        	ai.App_Listing__c=appIds[i] ;   
            
    		appIntList.add(ai);
		}
        upsert appIntList;  
                
        Lead emailLead = new Lead();
        emailLead = SendEmail(li[0]/*, appIntList*/);

    return l;      
    }
    
  
    @AuraEnabled
    Public Static Lead SendEmail(Lead lead/*, List<App_Interest__c> AppInt*/){
     try{
        //insert query for leadid
        Lead leadQ = [SELECT id, Name, Company, Email, Address, 
                      (SELECT Id FROM App_Interests__r) 
                      FROM Lead 
                	  WHERE Id = :lead.Id];
        EmailTemplate emailTemplate = [SELECT Id, Subject, HtmlValue, Body 
                                       FROM EmailTemplate 
                                       where Id ='00X1J000000jmuM'];
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setTemplateID(emailTemplate.Id); 
		mail.setSaveAsActivity(true);
        mail.setTargetObjectId(leadQ.Id);     
       // mail.setOrgWideEmailAddressId('0D2B0000000069Y');
        String[] toaddress = new String[]{leadQ.Id};    
        system.debug('ToAddress'+toaddress);
		mail.setToAddresses(toaddress);
		allmsg.add(mail);
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        List<Lead> li = new list <Lead>();
        leadQ.Email = '';
        li.add(leadQ);
        system.debug(li);
   		update li;
          return leadQ; 
    	}
    catch(Exception err){
    	System.debug(err);
                  return lead; 

		}
          
    }

    
    @AuraEnabled
    public static List<App_Listing__c> findAll() {
        return [SELECT id, Short_Name__c , Name, App_by_Partner__c, Tagline__c, Full_Description__c, Short_Description__c, Listing_Id__c, Pricing__c, Rating__c, Partner__r.Booth__c, Partner__r.Name
                FROM App_Listing__c 
                LIMIT 20];
    }
    
    
    @AuraEnabled
    public static List<App_Listing__c> findByName(String searchKey) {
        String name = '%' + searchKey + '%';
        //String booth = '%' + booth + '%'
        //String paid = paid
        //String rating = rating
        return [SELECT id, name, Short_Name__c, App_by_Partner__c, Tagline__c, Full_Description__c, Short_Description__c, Listing_Id__c, Pricing__c, Rating__c, Partner__r.Booth__c, Partner__r.Name 
                FROM App_Listing__c 
                WHERE name LIKE :name OR Tagline__c LIKE :name OR Partner__r.Name Like :name
                LIMIT 20];
    }  
   
    @AuraEnabled
    public static List<App_Listing__c> findById(List<Id> appListingId){  
        system.debug(appListingId);
        List<App_Listing__c> tempList = [SELECT id, name, App_by_Partner__c, Short_Name__c, Tagline__c, Short_Description__c,  Full_Description__c, Listing_Id__c, Pricing__c, Rating__c, Partner__r.Booth__c, Partner__r.Name 
                FROM App_Listing__c 
                WHERE Id IN :appListingId];
        
                system.debug(tempList);
        return tempList;        
    }   
   
    
    
}